// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type AssignPermissionReq struct {
	RoleID        int64   `json:"role_id"`        // 角色ID
	PermissionIDs []int64 `json:"permission_ids"` // 权限ID列表
}

type AssignPermissionRespData struct {
}

type AssignRoleReq struct {
	UserID  int64   `json:"user_id"`
	RoleIDs []int64 `json:"role_ids"`
}

type AssignRoleRespData struct {
}

type Captcha struct {
	CaptchaID     string `json:"captcha_id"`     // 验证码ID
	CaptchaValue  string `json:"captcha_value"`  // 验证码值
	CaptchaImage  string `json:"captcha_image"`  // 验证码图片（Base64编码）
	CaptchaExpire int64  `json:"captcha_expire"` // 验证码过期时间戳
}

type CheckPermissionReq struct {
	RoleID       int64 `json:"role_id"`       // 角色ID
	PermissionID int64 `json:"permission_id"` // 权限ID
}

type CheckPermissionRespData struct {
	HasPermission bool `json:"has_permission"` // 是否拥有权限
}

type CreatePermissionReq struct {
	Name        string `json:"name"`        // 权限名称
	Description string `json:"description"` // 权限描述
}

type CreatePermissionRespData struct {
	ID int64 `json:"id"` // 新权限ID
}

type CreateRoleReq struct {
	RoleCode    string `json:"role_code"`   // 角色唯一编码，例如 "admin"
	RoleName    string `json:"role_name"`   // 角色名称，例如 "管理员"
	Description string `json:"description"` // 角色的描述信息
}

type CreateRoleRespData struct {
	Role Role `json:"role"`
}

type CreateUserReq struct {
	Username   string `json:"username"`   // 用户名
	Password   string `json:"password"`   // 密码
	Realname   string `json:"realname"`   // 真实姓名
	Email      string `json:"email"`      // 邮箱
	Phone      string `json:"phone"`      // 电话
	Department string `json:"department"` // 部门
}

type CreateUserRespData struct {
	User User `json:"user"` // 返回的用户信息
}

type DeletePermissionReq struct {
	ID int64 `json:"id"` // 权限ID
}

type DeletePermissionRespData struct {
}

type DeleteRoleReq struct {
	ID int64 `json:"id"`
}

type DeleteRoleRespData struct {
}

type DeleteUserReq struct {
	UserName string `json:"user_name"` // 用户名
}

type DeleteUserRespData struct {
	User User `json:"user"` // 返回的用户信息
}

type DetachPermissionReq struct {
	RoleID        int64   `json:"role_id"`        // 角色ID
	PermissionIDs []int64 `json:"permission_ids"` // 权限ID列表
}

type DetachPermissionRespData struct {
}

type DetachRoleReq struct {
	UserID  int64   `json:"user_id"`
	RoleIDs []int64 `json:"role_ids"`
}

type DetachRoleRespData struct {
}

type DingTalkLoginReq struct {
	AuthCode string `json:"auth_code"` // 钉钉授权码
}

type DingTalkLoginRespData struct {
	OpenID      string `json:"openid"`       // 用户 OpenID
	Nickname    string `json:"nickname"`     // 用户昵称
	UnionID     string `json:"unionid"`      // 用户 UnionID
	AccessToken string `json:"access_token"` // 访问令牌
	ExpiresIn   int    `json:"expires_in"`   // 令牌有效期
}

type GetCaptchaReq struct {
}

type GetCaptchaResp struct {
	Captcha Captcha `json:"captcha"` // 验证码信息
}

type GetPermissionReq struct {
	ID int64 `json:"id"` // 权限ID
}

type GetPermissionRespData struct {
	Permission Permission `json:"permission"` // 权限数据
}

type GetRoleReq struct {
	ID int64 `json:"id"`
}

type GetRoleRespData struct {
	Role Role `json:"role"`
}

type GetUserInfoReq struct {
	Username string `json:"username"` // 用户名
}

type GetUserInfoRespData struct {
	UserInfo UserInfo `json:"userinfo"` // 用户信息
}

type GetUserReq struct {
	UserName string `json:"user_name"` // 用户名
}

type GetUserRespData struct {
	User User `json:"user"` // 返回的用户信息
}

type HealthReq struct {
}

type HealthResp struct {
	Status string `json:"status"` // 服务状态
}

type ListPermissionsReq struct {
	Page     int    `json:"page"`      // 页码
	PageSize int    `json:"page_size"` // 每页数量
	Sort     string `json:"sort"`      // 排序方式（如：asc/desc）
}

type ListPermissionsRespData struct {
	Total       int64        `json:"total"`       // 总数
	Permissions []Permission `json:"permissions"` // 权限列表
}

type ListRolesReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
	Sort     string `json:"sort"`
}

type ListRolesRespData struct {
	Total int64  `json:"total"`
	Roles []Role `json:"roles"`
}

type ListUsersReq struct {
	Page     int    `json:"page"`      // 当前页
	PageSize int    `json:"page_size"` // 每页大小
	Sort     string `json:"sort"`      // 排序字段
}

type ListUsersRespData struct {
	Total int    `json:"total"` // 总用户数
	Users []User `json:"users"` // 用户列表
}

type LoginReq struct {
	Username     string `json:"username"`      // 用户名
	Password     string `json:"password"`      // 密码
	CaptchaId    string `json:"captcha_id"`    // 验证码ID
	CaptchaValue string `json:"captcha_value"` // 验证码值
}

type LoginRespData struct {
	Tokens   SessionToken `json:"tokens"`   // 会话令牌
	UserInfo UserInfo     `json:"userinfo"` // 用户信息
}

type LogoutReq struct {
	Username     string `json:"username"`      // 用户名
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type LogoutRespData struct {
}

type Permission struct {
	ID          int64  `json:"id"`          // 权限ID
	Name        string `json:"name"`        // 权限名称
	Description string `json:"description"` // 权限描述
	CreatedAt   string `json:"created_at"`  // 创建时间
	CreateBy    string `json:"create_by"`   // 角色创建人
	UpdatedAt   string `json:"updated_at"`  // 更新时间
	UpdateBy    string `json:"update_by"`   // 角色更新人
}

type RefreshTokenReq struct {
	Username     string `json:"username"`      // 用户名
	RefreshToken string `json:"refresh_token"` // 刷新令牌
}

type RefreshTokenRespData struct {
	Tokens SessionToken `json:"tokens"` // 会话令牌
}

type RegisterReq struct {
	Username     string `json:"username"`      // 用户名
	Password     string `json:"password"`      // 密码
	Email        string `json:"email"`         // 邮箱
	Phone        string `json:"phone"`         // 电话号码
	CaptchaId    string `json:"captcha_id"`    // 验证码ID
	CaptchaValue string `json:"captcha_value"` // 验证码值
}

type RegisterRespData struct {
}

type ResetPasswordReq struct {
	UserName        string `json:"user_name"`        // 用户名
	Password        string `json:"password"`         // 新密码
	ConfirmPassword string `json:"confirm_password"` // 确认密码
}

type ResetPasswordRespData struct {
}

type Result struct {
	Code    int64       `json:"code"`    // 响应码
	Message string      `json:"message"` // 响应消息
	Data    interface{} `json:"data"`    // 返回数据，可以是任何类型 //any
}

type Role struct {
	ID          int64  `json:"id"`          // 角色ID
	RoleCode    string `json:"role_code"`   // 角色唯一编码，例如 "admin"
	RoleName    string `json:"role_name"`   // 角色名称，例如 "管理员"
	Description string `json:"description"` // 角色的描述信息
	Status      int8   `json:"status"`      // 角色状态
	DelFlag     int8   `json:"del_flag"`    // 删除状态
	CreateBy    string `json:"create_by"`   // 角色创建人
	CreateAt    string `json:"create_at"`   // 角色创建时间
	UpdateBy    string `json:"update_by"`   // 角色更新人
	UpdateAt    string `json:"update_at"`   // 角色更新时间
}

type SearchUsersReq struct {
	Query    string `json:"query"`     // 搜索关键词
	Page     int    `json:"page"`      // 页码
	PageSize int    `json:"page_size"` // 每页数量
}

type SearchUsersRespData struct {
	Total int    `json:"total"` // 总用户数
	Users []User `json:"users"` // 用户列表
}

type SessionToken struct {
	AccessToken   string `json:"access_token"`   // 访问令牌
	RefreshToken  string `json:"refresh_token"`  // 刷新令牌
	AccessExpire  int64  `json:"access_expire"`  // 访问令牌过期时间戳
	RefreshExpire int64  `json:"refresh_expire"` // 刷新令牌过期时间戳
}

type SysStatus struct {
	CpuTotal  int64   `json:"cpu_total"`  // CPU总核数
	CpuUsage  float64 `json:"cpu_usage"`  // CPU使用率
	MemTotal  int64   `json:"mem_total"`  // 内存总大小
	MemUsage  float64 `json:"mem_usage"`  // 内存使用率
	DiskTotal int64   `json:"disk_total"` // 磁盘总大小
	DiskUsage float64 `json:"disk_usage"` // 磁盘使用率
}

type SysStatusReq struct {
}

type SysStatusResp struct {
	SysStatus SysStatus `json:"sys_status"` // 系统状态
}

type TokenReq struct {
	GrantType    string `json:"grant_type"`              // 授权类型 (authorization_code, client_credentials, refresh_token)
	ClientID     string `json:"client_id"`               // 客户端 ID
	ClientSecret string `json:"client_secret"`           // 客户端密钥
	Code         string `json:"code,omitempty"`          // 授权码 (仅 authorization_code 需要)
	RedirectURI  string `json:"redirect_uri,omitempty"`  // 重定向 URI (仅 authorization_code 需要)
	RefreshToken string `json:"refresh_token,omitempty"` // 刷新令牌 (仅 refresh_token 需要)
}

type TokenRspData struct {
	AccessToken  string `json:"access_token"`            // 访问令牌
	TokenType    string `json:"token_type"`              // 令牌类型 (默认 Bearer)
	ExpiresIn    int    `json:"expires_in"`              // 过期时间 (秒)
	RefreshToken string `json:"refresh_token,omitempty"` // 刷新令牌
}

type UpdatePasswordReq struct {
	Username        string `json:"username"`         // 用户名
	OldPassword     string `json:"old_password"`     // 旧密码
	NewPassword     string `json:"new_password"`     // 新密码
	ConfirmPassword string `json:"confirm_password"` // 确认密码
}

type UpdatePasswordRespData struct {
}

type UpdatePermissionReq struct {
	ID          int64  `json:"id"`          // 权限ID
	Name        string `json:"name"`        // 权限名称
	Description string `json:"description"` // 权限描述
}

type UpdatePermissionRespData struct {
	Permission Permission `json:"permission"` // 更新后的权限数据
}

type UpdateRoleReq struct {
	ID          int    `json:"id"`          // 角色ID
	RoleCode    string `json:"role_code"`   // 角色编码
	RoleName    string `json:"role_name"`   // 角色名称
	Description string `json:"description"` // 角色描述
	Status      int8   `json:"status"`      // 角色状态
}

type UpdateRoleRespData struct {
	Role Role `json:"role"`
}

type UpdateUserInfoReq struct {
	Username string   `json:"username"` // 用户名
	UserInfo UserInfo `json:"userinfo"` // 用户信息
}

type UpdateUserInfoRespData struct {
	UserInfo UserInfo `json:"userinfo"` // 用户信息
}

type UpdateUserReq struct {
	User User `json:"user"` // 用户信息
}

type UpdateUserRespData struct {
	User User `json:"user"` // 返回的用户信息
}

type UpdateUserStatusReq struct {
	UserName string `json:"user_name"` // 用户名
	Status   int8   `json:"status"`    // 状态
}

type UpdateUserStatusRespData struct {
	User User `json:"user"` // 返回的用户信息
}

type User struct {
	ID                   int64  `json:"id"`                      // 用户ID
	Username             string `json:"username"`                // 用户名
	Realname             string `json:"realname"`                // 真实姓名
	Email                string `json:"email"`                   // 邮箱
	Phone                string `json:"phone"`                   // 电话
	RoleCode             string `json:"role_code"`               // 角色编码
	RoleName             string `json:"role_name"`               // 角色名称
	Status               int8   `json:"status"`                  // 状态
	DelFlag              int8   `json:"del_flag"`                // 删除标志
	Remark               string `json:"remark"`                  // 备注
	CreateBy             string `json:"create_by"`               // 创建人
	CreateAt             int64  `json:"create_at"`               // 创建时间 (Unix 时间戳)
	UpdateBy             string `json:"update_by"`               // 更新人
	UpdateAt             int64  `json:"update_at"`               // 更新时间 (Unix 时间戳)
	ClientIP             string `json:"client_ip"`               // 客户端IP
	FailedCnt            int64  `json:"failed_cnt"`              // 登录失败次数
	Nickname             string `json:"nickname"`                // 昵称
	Department           string `json:"department"`              // 部门
	EnName               string `json:"en_name"`                 // 英文名
	Avatar               string `json:"avatar"`                  // 头像
	IsAdmin              bool   `json:"is_admin"`                // 是否为管理员
	LastLoginAt          int64  `json:"last_login_at"`           // 最后登录时间 (Unix 时间戳)
	CreatedIP            string `json:"created_ip"`              // 创建时IP
	LastPasswordChangeAt int64  `json:"last_password_change_at"` // 最后修改密码时间 (Unix 时间戳)
	TwoFactorEnabled     bool   `json:"two_factor_enabled"`      // 是否启用双重认证
}

type UserInfo struct {
	ID         int64  `json:"id"`                   // 用户ID
	Username   string `json:"username"`             // 用户名
	Realname   string `json:"realname"`             // 真实姓名
	Email      string `json:"email"`                // 邮箱
	Phone      string `json:"phone"`                // 电话号码
	Remark     string `json:"remark,omitempty"`     // 备注
	Nickname   string `json:"nickname,omitempty"`   // 昵称
	Department string `json:"department,omitempty"` // 部门
	EnName     string `json:"en_name,omitempty"`    // 英文名
	Avatar     string `json:"avatar,omitempty"`     // 头像
}
