stages:
  - build

build:
  stage: build
  script:
    - whoami
    - pwd
    - go mod tidy
    - go build -o /var/api/genops-master/master-api genops-master
    - cp -r ./etc /var/api/genops-master/etc