CREATE TABLE Role (
    ID INT(32) AUTO_INCREMENT COMMENT '角色ID',
    RoleCode VARCHAR(25) UNIQUE NOT NULL COMMENT '角色编码',
    RoleName VARCHAR(100) NOT NULL COMMENT '角色名称',
    Description VARCHAR(255) COMMENT '角色描述',
    Status TINYINT(1) DEFAULT 1 COMMENT '状态(1-正常,2-禁用)',
    DelFlag TINYINT(1) DEFAULT 0 COMMENT '删除状态(0-正常,1-已删除)',
    CreateBy VARCHAR(32) COMMENT '创建人',
    CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateBy VARCHAR(32) COMMENT '更新人',
    UpdateTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';
