CREATE TABLE Permission (
    ID INT(32) AUTO_INCREMENT COMMENT '权限ID',
    Name VARCHAR(100) UNIQUE NOT NULL COMMENT '权限名称',
    Description VARCHAR(255) COMMENT '权限描述',
    CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';
