CREATE TABLE RolePermission (
    ID INT(32) AUTO_INCREMENT COMMENT '主键ID',
    RoleCode VARCHAR(25) NOT NULL COMMENT '角色编码',
    PermissionID INT(32) NOT NULL COMMENT '权限ID',
    CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateTime TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (RoleCode) REFERENCES Users(RoleCode),
    FOREIGN KEY (PermissionID) REFERENCES Permission(ID),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关联表';
