CREATE TABLE ServiceFunction (
    ID INT UNSIGNED AUTO_INCREMENT COMMENT '主键ID',
    Name VARCHAR(255) NOT NULL COMMENT '名称',
    Description TEXT COMMENT '描述',
    Permission VARCHAR(50) COMMENT '权限',
    Visibility TINYINT(1) DEFAULT 1 COMMENT '是否可见',
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdatedAt TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务功能表';
