CREATE TABLE UserRole (
    ID INT AUTO_INCREMENT COMMENT '主键ID',
    UserID INT NOT NULL COMMENT '用户ID',
    RoleCode VARCHAR(25) NOT NULL COMMENT '角色编码',
    CreateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UpdateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (RoleCode) REFERENCES Role(RoleCode),
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关联表';
